**Data Analysis with Python Week 1 Session**

In [ ]:
# Importing a package
# Import package_name as alias name
import numpy as np
# Create an array
# arrayname = alias.name.array([v1,v2,v3,..vn])
# 1-D array
a= np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
# 2-D array
# arrayname=aliasname.array([[d1][d2]])
b= np.array([[1,2,3,4,5,6,],[1,2,3,4,5,6,]])
b

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [ ]:
# 3-D array
# arrayname=aliasname.array([[d1][d2][d3]])
c= np.array([[1,2,3],[1,2,3,],[4,5,6],[8,9,10]])
c

array([[ 1,  2,  3],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [ ]:
# Attributes --> dimensions,shape,size
# Dimensions- Number of dimensions--> ndim--> arrayname.ndim
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
c.ndim

2

In [ ]:
# Size --> Finding total number of elements in an array --> arrayname.size
a.size

4

In [ ]:
b.size

12

In [ ]:
c.size

12

In [ ]:
# Minimum --> min(arrayname) or np.min(a)
min(a)

1

In [ ]:
np.min(a)

1

In [ ]:
np.min(b)

1

In [ ]:
np.min(c)

1

In [ ]:
# Maximum --> max(arrayname) or np.max(a)
max(a)

4

In [ ]:
np.max(a)

4

In [ ]:
np.max(b)

6

In [ ]:
np.max(c)

10

In [ ]:
# Index position of min & max --> argmin() & argmax()
# argmin()--> Index pos of min
# argmax()--> Index pos of max
# Syntax --> aliasname.argmin(arrayname),aliasname.argmin(arrayname)
# Syntax --> aliasname.argmin(arrayname),aliasname.argmax(arrayname)
np.argmin(a)

0

In [ ]:
np.argmax(a)

3

In [ ]:
# Sum of array
# Syntax --> sum(arrayname) or np.sum(arrayname)
sum(a)

10

In [ ]:
np.sum(a)

10

In [ ]:
# Product of array
# Syntax --> np.prod(arrayname)
np.prod(a)

24

In [ ]:
# Mean of array
# Syntax --> np.mean(arrayname)
np.mean(a)

2.5

In [ ]:
# Median of array
# Syntax --> np.median(arrayname)
np.median(a)

2.5

In [ ]:
# Variance of array
# Syntax --> np.var(arrayname)
np.var(a)

1.25

In [ ]:
# Height -- Dataset -- Application
import numpy as np
import pandas as pd
data = pd.read_csv(r"/content/heights.csv")
heights = np.array(data['height'])
print(heights)
# Statistical metrics of the Heights Dataset
print("Minimum Height:", heights.min())
print("Sum:",np.sum(heights))
print("Min Index:",np.argmin(heights))
print("Max Index:",np.argmax(heights))
print("Variance:", np.var(heights))
print("Average Height:",heights.mean())
print("Maximum Height:", heights.max())
print("25th Percentile:",np.percentile(heights,25))
print("Median:",np.median(heights))
print("75th Percentile:",np.percentile(heights,75))

[74.42443878 65.53754283 63.62919774 ... 63.66416353 71.9258358
 68.36848621]
Minimum Height: 57.5032186105382
Sum: 79762.86328320228
Min Index: 428
Max Index: 576
Variance: 14.8406074828533
Average Height: 66.91515376107574
Maximum Height: 77.0512818135321
25th Percentile: 64.0097456309595
Median: 66.4512652109843
75th Percentile: 69.84810005291368
