**Data Analysis with Python Week 10 Session**

In [ ]:
# Importing a package
# Import package_name as alias name
import numpy as np
# Create an 2-D array
# arrayname=aliasname.array([[d1][d2]])
a=np.array([[1,2,3],[4,5,6],[6,7,8]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
# Swapping the rows of a given array in reverse order
# Syntax --> reversed_arrayname = arrayname[::-1,::]
b=a[::-1,::]
b

array([[6, 7, 8],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
# Swapping the coloumns of a given array in reverse order
# Syntax --> reversed_arrayname = arrayname[:,::-1]
c=a[:,::-1]
c

array([[3, 2, 1],
       [6, 5, 4],
       [8, 7, 6]])

In [ ]:
# Swapping both rows and coloumns of a given array in reverse order
# Syntax --> reversed_arrayname = arrayname[::-1,::-1]
d=a[::-1,::-1]
d

array([[8, 7, 6],
       [6, 5, 4],
       [3, 2, 1]])