**Data Analysis with Python Week 11 Session**

In [ ]:
# Importing a package
# Import package_name as alias name
import numpy as np
# Create an 2-D array
# arrayname=aliasname.array([[d1][d2]]
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
'''Computing the mean, median, standard deviation, and variance of a given array
   along the second axis'''
# Syntax --> np.mean(arrayname, axis=1)
# Syntax --> np.median(arrayname, axis=1)
# Syntax --> np.std(arrayname, axis=1)
# Syntax --> np.var(arrayname, axis=1)
mean = np.mean(a, axis=1)
median=np.median(a, axis=1)
std_dev = np.std(a, axis=1)
variance = np.var(a, axis=1)
'''Printing the mean, median, standard deviation, and variance of a given array
   along the second axis'''
print("Mean along the second axis:", mean)
print("Median along the second axis:", median)
print("Standard deviation along the second axis:", std_dev)
print("Variance along the second axis:", variance)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Mean along the second axis: [ 2.5  6.5 10.5]
Median along the second axis: [ 2.5  6.5 10.5]
Standard deviation along the second axis: [1.11803399 1.11803399 1.11803399]
Variance along the second axis: [1.25 1.25 1.25]


In [ ]:
'''Computing the mean, median, standard deviation, and variance of a given array
   along the first axis'''
# Syntax --> np.mean(arrayname, axis=0)
# Syntax --> np.median(arrayname, axis=0)
# Syntax --> np.std(arrayname, axis=0)
# Syntax --> np.var(arrayname, axis=0)
mean = np.mean(a, axis=0)
median=np.median(a, axis=0)
std_dev = np.std(a, axis=0)
variance = np.var(a, axis=0)
'''Printing the mean, median, standard deviation, and variance of a given array
   along the first axis'''
print("Mean along the second axis:", mean)
print("Median along the second axis:", median)
print("Standard deviation along the second axis:", std_dev)
print("Variance along the second axis:", variance)

Mean along the second axis: [5. 6. 7. 8.]
Median along the second axis: [5. 6. 7. 8.]
Standard deviation along the second axis: [3.26598632 3.26598632 3.26598632 3.26598632]
Variance along the second axis: [10.66666667 10.66666667 10.66666667 10.66666667]
