**Data Analysis with Python Week 2 Session**

In [ ]:
# Importing a package
# Import package_name as alias name
import numpy as np
# Create an array
# arrayname = alias.name.array([v1,v2,v3,..vn])
# 1-D array
a= np.array([1,2,3,4,5])
print(a)
# Comparisions --> <,<=,>,>=,==,!=
# aliasname.comparision(array_1,array_2)
# Less Than Operator
print(np.less(a,3))
print(a<3)
# Less Than and Equal to Operator
print(np.less_equal(a,3))
print(a<=3)
# Greater Than Operator
print(np.greater(a,4))
print(a>4)
# Greater Than and Equal to Operator
print(np.greater_equal(a,4))
print(a>=4)
# Equal To Operator
print(np.equal(a,3))
print(a==3)
# Not Equal To Operator
print(np.not_equal(a,4))
print(a!=4)

[1 2 3 4 5]
[ True  True False False False]
[ True  True False False False]
[ True  True  True False False]
[ True  True  True False False]
[False False False False  True]
[False False False False  True]
[False False False  True  True]
[False False False  True  True]
[False False  True False False]
[False False  True False False]
[ True  True  True False  True]
[ True  True  True False  True]


In [ ]:
# Boolean Logic Operators --> and(&),or(|),not(~)
b= np.array([1,2,3,4,5])
print(b)
# Logical AND Operator
print(np.logical_and(a,b))
print(a & b)
c= (a<b)&(a>b)
c
# Logical OR Operator
print(np.logical_or(a,b))
print(a | b)
d= (a<b)|(a>b)
d
# Logical NOT Operator
print(np.logical_not(a))
print(~a)

[1 2 3 4 5]
[ True  True  True  True  True]
[1 2 3 4 5]
[ True  True  True  True  True]
[1 2 3 4 5]
[False False False False False]
[-2 -3 -4 -5 -6]


In [1]:
# Importing a package
# Import package_name as alias name
import numpy as np
# Create an array
# arrayname = alias.name.array([v1,v2,v3,..vn])
# 1-D array
a= np.array([1,2,3,4,5])
# Masking --> Manipulation of the array to remove the unwanted array elements
print(a[a<5])
print(a+3)
print(a*3)

[1 2 3 4]
[4 5 6 7 8]
[ 3  6  9 12 15]


In [ ]:
import numpy as np
import pandas as pd
data = pd.read_csv(r"/content/Student_Marks.csv")
Marks = np.array(data['Marks'])
print(Marks)
# Comparisons
print("\nMarks less than 50:", np.less(marks, 50))
print("Marks less than or equal to 50:", np.less_equal(marks, 50))
print("Marks greater than 70:", np.greater(marks, 70))
print("Marks greater than or equal to 75:", np.greater_equal(marks, 75))
print("Marks equal to 72:", np.equal(marks, 72))
print("Marks not equal to 51:", np.not_equal(marks, 51))

# Boolean Logic Operations
pass_marks = np.array([50] * len(marks))
print("\nLogical AND (Marks and pass marks):", np.logical_and(marks, pass_marks))
print("Logical OR (Marks or pass marks):", np.logical_or(marks, pass_marks))
print("Logical NOT (Marks):", np.logical_not(marks))

# Masking
print("\nMarks less than 50 (masked):", marks[marks < 50])
print("Marks greater than 70 (masked):", marks[marks > 70])

# Operations on the dataset
print("\nMarks + 5:", marks + 5)
print("Marks * 2:", marks * 2)

[19.202  7.734 13.811 53.018 55.299 17.822 29.889 17.264 20.348 30.862
 42.036 12.132 24.318 17.672 11.397 19.466 30.548 38.49  50.986 25.133
 22.073 35.939 12.209 28.043 16.517  6.623 12.647 26.532  9.333  8.837
 24.172  8.1   15.038 39.965 17.171 43.978 13.119 46.453 41.358 51.142
  7.336 15.725 19.771 10.429  9.742  8.924 16.703 22.701 26.882 19.106
 40.602 22.184  7.892 36.653 53.158 18.238 53.359 51.583 31.236 51.343
 10.522 10.844 19.59  21.379 12.591 13.562 27.569  6.185  8.92  21.4
 16.606 13.416 20.398  7.014 39.952  6.217 36.746 38.278 49.544  6.349
 54.321 17.705 44.099 16.106 16.461 39.957 23.149  6.053 11.253 40.024
 24.394 19.564 23.916 42.426 24.451 19.128  5.609 41.444 12.027 32.357]

Marks less than 50: [ True False False False  True False False  True False False]
Marks less than or equal to 50: [ True False False False  True False False  True False False]
Marks greater than 70: [False  True  True False False False  True False  True  True]
Marks greater than or equal t